# Generated by Django 2.2.3 on 2019-08-21 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('slug', models.CharField(help_text="Значение статуса, хранящееся в БД(например для title='отклонено' возможные slug='RJ')", max_length=2, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Наименование статуса (желательно в 3-м лице)', max_length=64, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ID', 'Идея'), ('TH', 'Благодарность'), ('PR', 'Проблема'), ('QU', 'Вопрос')], default='ID', help_text='Тип отзыва', max_length=2)),
                ('title', models.CharField(help_text='Заголовок отзыва', max_length=128)),
                ('content', models.TextField(help_text='Содержание отзыва')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pub_state', models.CharField(choices=[('DR', 'Черновик'), ('PB', 'Опубликовано')], default='DR', help_text='Состояние публикации отзыва', max_length=2)),
                ('author', models.ForeignKey(blank=True, help_text='Автор отзыва', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(blank=True, help_text='Пользователи, которым не понравился отзыв', related_name='dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, help_text='Пользователи, которым понравился отзыв', related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default='WA', help_text='Состояние обработки отзыва', on_delete=django.db.models.deletion.CASCADE, to='reviews.Status')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Содержание комментария')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pub_state', models.CharField(choices=[('DR', 'Черновик'), ('PB', 'Опубликовано')], default='DR', help_text='Состояние публикации комментария', max_length=2)),
                ('author', models.ForeignKey(help_text='Автор комментария', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(help_text='Отзыв, к которому был оставлен комментарий', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.Review')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
