# Generated by Django 2.2.3 on 2020-09-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rprofiletest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Тип вопроса. 1 или 2', max_length=30)),
                ('question_text', models.CharField(help_text='Текст вопроса', max_length=200)),
            ],
        ),
    ]
