# Generated by Django 2.2.3 on 2020-09-01 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rprofiletest',
            new_name='Question',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Текст ответа', max_length=30)),
                ('score', models.CharField(help_text='Баллы за ответ', max_length=30)),
                ('question', models.ForeignKey(help_text='Ответ', on_delete=django.db.models.deletion.CASCADE, to='rprofile.Question')),
            ],
        ),
    ]
