# Generated by Django 2.2.3 on 2020-09-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rprofile', '0002_auto_20200901_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='Ответ', on_delete=django.db.models.deletion.PROTECT, to='rprofile.Question'),
        ),
    ]
