# Generated by Django 2.2.3 on 2020-09-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rprofile', '0003_auto_20200901_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
