# Generated by Django 2.2.3 on 2020-09-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rprofile', '0004_auto_20200901_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_text',
            field=models.CharField(default='', help_text='Текст вопроса', max_length=200),
            preserve_default=False,
        ),
    ]
