# Generated by Django 2.2.3 on 2020-09-02 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rprofile', '0005_answer_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='Вопрос', on_delete=django.db.models.deletion.PROTECT, to='rprofile.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.IntegerField(help_text='Баллы за ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(help_text='Текст ответа', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(help_text='Текст вопроса', max_length=300),
        ),
    ]
