# Generated by Django 2.2.3 on 2020-09-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rprofile', '0006_auto_20200902_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_text',
            field=models.CharField(help_text='Текст вопроса', max_length=300),
        ),
    ]
