# Generated by Django 2.2.3 on 2020-09-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rprofile', '0007_auto_20200902_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question_text',
        ),
    ]
