# Generated by Django 3.1.1 on 2020-10-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rprofile', '0008_remove_answer_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='number',
            field=models.IntegerField(default=1, help_text='Вариант ответа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(default=1, help_text='Номер вопроса'),
            preserve_default=False,
        ),
    ]
