# Generated by Django 3.1.1 on 2020-11-18 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_portfolio_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rprofile', '0009_auto_20201006_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_name', models.CharField(max_length=250)),
                ('result_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_test_results', to='account.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_test_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
