# Generated by Django 3.1.1 on 2020-12-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rprofile', '0011_auto_20201207_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskProfileVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_version', models.IntegerField(help_text='Текущая версия')),
            ],
            options={
                'verbose_name': 'Версия риск-профиля',
                'verbose_name_plural': 'Версии риск-профиля',
            },
        ),
        migrations.AddField(
            model_name='rtestresult',
            name='acceptable_risk_value',
            field=models.CharField(help_text='Допустимое значение риска, 1 год', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rtestresult',
            name='capacity',
            field=models.CharField(help_text='Возможность принятия риска', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rtestresult',
            name='description',
            field=models.TextField(help_text='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rtestresult',
            name='indexRC',
            field=models.IntegerField(help_text='Индекс capacity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rtestresult',
            name='indexRT',
            field=models.IntegerField(help_text='Индекс tolerance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rtestresult',
            name='notification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtestresult',
            name='number',
            field=models.CharField(help_text='Номер профиля', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rtestresult',
            name='portfolio',
            field=models.TextField(help_text='Модельный портфель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rtestresult',
            name='portfolio_description',
            field=models.TextField(help_text='Описание модельного портфеля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rtestresult',
            name='tolerance',
            field=models.CharField(help_text='Отношение к риску', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rtestresult',
            name='version',
            field=models.IntegerField(help_text='Версия риск-профиля'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rtestresult',
            name='result_name',
            field=models.CharField(help_text='Название профиля', max_length=250),
        ),
    ]
