# Generated by Django 2.2.3 on 2020-06-02 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtest', '0020_auto_20200407_2007'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аккаунт пользователя',
                'verbose_name_plural': 'Аккаунты пользователей',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_portfolios', to='account.Account')),
            ],
            options={
                'verbose_name': 'Портфель',
                'verbose_name_plural': 'Портфели',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата транзакции')),
                ('operation_type', models.CharField(choices=[('input', 'input'), ('output', 'output'), ('buy', 'buy'), ('sale', 'sale'), ('dividend', 'dividend')], max_length=8, verbose_name='Тип операции')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('cost', models.IntegerField(verbose_name='Общая стоимость')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtest.Asset', verbose_name='Актив')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_transactions', to='account.Portfolio')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
