# Generated by Django 2.2.3 on 2020-06-02 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аккаунт пользователя',
                'verbose_name_plural': 'Аккаунты пользователей',
            },
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_portfolios', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operation_type',
            field=models.CharField(choices=[('input', 'input'), ('output', 'output'), ('покупка', 'покупка'), ('продажа', 'продажа'), ('dividend', 'dividend')], max_length=8, verbose_name='Тип операции'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
