# Generated by Django 2.2.3 on 2020-06-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200602_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='account',
            new_name='profile',
        ),
    ]
