# Generated by Django 2.2.3 on 2020-06-05 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0021_auto_20200602_1720'),
        ('account', '0004_auto_20200603_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='benchmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backtest.Asset'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backtest.Currency'),
        ),
    ]
