# Generated by Django 2.2.3 on 2020-06-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200605_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='count',
            field=models.IntegerField(blank=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='price',
            field=models.IntegerField(blank=True, verbose_name='Цена'),
        ),
    ]
