# Generated by Django 2.2.3 on 2020-06-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200611_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='count',
            field=models.IntegerField(null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
    ]
