# Generated by Django 2.2.3 on 2020-07-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200611_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('id',), 'verbose_name': 'Портфель', 'verbose_name_plural': 'Портфели'},
        ),
        migrations.AlterField(
            model_name='operation',
            name='cost',
            field=models.FloatField(verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='count',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
