# Generated by Django 2.2.3 on 2020-08-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200721_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['-date', '-pk'], 'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AlterModelOptions(
            name='operationtype',
            options={'ordering': ('-order',), 'verbose_name': 'Тип операции', 'verbose_name_plural': 'Типы операций'},
        ),
        migrations.AddField(
            model_name='operationtype',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок в выавдающем списке'),
        ),
    ]
