# Generated by Django 2.2.3 on 2020-09-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200802_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationtype',
            options={'ordering': ('order',), 'verbose_name': 'Тип операции', 'verbose_name_plural': 'Типы операций'},
        ),
    ]
