# Generated by Django 3.1.1 on 2020-10-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200906_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tg_token',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
