# Generated by Django 3.1.1 on 2020-10-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_profile_tg_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='', help_text='Имя портфолио', max_length=300),
        ),
    ]
