# Generated by Django 3.1.1 on 2020-11-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_portfolio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tg_chat_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
