# Generated by Django 3.1.1 on 2020-11-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_profile_tg_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
