# Generated by Django 3.1.1 on 2020-11-18 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rprofile', '0010_rtestresult'),
        ('account', '0015_portfolio_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='actual_r_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_r_test_results', to='rprofile.rtestresult'),
        ),
    ]
