# Generated by Django 3.1.1 on 2020-12-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_profile_actual_r_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_sent_notify_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='send_notify_at',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
    ]
