# Generated by Django 3.1.1 on 2020-12-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20201204_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_sent_notify_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='send_notify_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='send_notify_dividends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='send_notify_dividends_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='send_notify_report_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='send_notify_report_date_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
