# Generated by Django 3.1.1 on 2021-01-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20201215_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='send_daily_notify_dividends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='send_daily_notify_report_date_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
