# Generated by Django 3.1.1 on 2021-01-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20210112_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='send_daily_notify_dividends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='send_daily_notify_report_date',
            field=models.BooleanField(default=False),
        ),
    ]
