# Generated by Django 3.1.1 on 2021-03-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20210114_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
