"""
Django settings for WealthView project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from django.core.exceptions import ImproperlyConfigured
from django.urls import reverse_lazy

def get_env_value(env_variable):
    try:
        return os.environ[env_variable]
    except KeyError:
        error_msg = 'Set the {} environment variable'.format(env_variable)
        raise ImproperlyConfigured(error_msg)


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

REQUESTS_LOG_ENABLED = os.getenv('REQUESTS_LOG_ENABLED', 1)
BOT_SECRET = os.getenv('BOT_SECRET')
BOT_USERNAME = os.getenv('BOT_USERNAME')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-oy(sr^(x#jpw-ucf2k#4ch&8y1a#uoipd5b)ju(6lw$@e(a1='

ENVIRONMENT = os.environ.get('ENVIRONMENT', "LOCAL")
IS_LOCAL_ENVIRONMENT = ENVIRONMENT == 'LOCAL'
IS_PRODUCTION_ENVIRONMENT = ENVIRONMENT == 'PRODUCTION'

# SECURITY WARNING: don't run with debug turned on in production!
if IS_PRODUCTION_ENVIRONMENT:
    DEBUG = False
else:
    DEBUG = True

SENTRY_DSN = None
if ENVIRONMENT == 'PRODUCTION':
    SENTRY_DSN = 'https://493cf6bdd720432682c534a32fd218fb@o447908.ingest.sentry.io/5478152'
if ENVIRONMENT == 'DEVELOP':
    SENTRY_DSN = "https://e39d6d43772a4e1e832e1c1cb087e77f@o447908.ingest.sentry.io/5478151"

if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=1.0,
        send_default_pii=True
    )

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.postgres',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'main',
    'api',
    'auth_sys',
    'account',
    'articles',
    'backtest',
    'rest_framework',
    'rprofile',
    'faq',
    'debug_toolbar',
    'reviews',
    "tinymce",
    "query_tools",
    'django_celery_beat',
    'algorithm',
    'django_db_logger',
    # 'silk',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
    # 'silk.middleware.SilkyMiddleware',
    'core.middleware.RequestLoggerMiddleware',
    'core.middleware.LoginRequiredMiddleware',
]

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

ROOT_URLCONF = 'WealthView.urls'

MASTER_BASE_DIR = os.path.dirname(__file__)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates', 'static', 'web/templates', 'web/static'],
        # 'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.environment',
            ],
        },
    },
]

ASGI_APPLICATION = 'WealthView.asgi.application'
WSGI_APPLICATION = 'WealthView.wsgi.application'

REDIS_HOST = os.environ.get('REDIS_HOST', 'redis')
REDIS_PORT = '6379'
CELERY_BROKER_URL = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
CELERY_BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}
CELERY_RESULT_BACKEND = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
CELERY_IMPORTS = ['algorithm.eod_service', 'algorithm.mvp_personal_account']
CELERY_ACCEPT_CONTENT = ['custom_json']
CELERY_TASK_SERIALIZER = 'custom_json'
CELERY_RESULT_SERIALIZER = 'custom_json'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': get_env_value('DATABASE_NAME'),
        'USER': get_env_value('DATABASE_USER_NAME'),
        'CONN_MAX_AGE': 0,
        'PASSWORD': get_env_value('DATABASE_PASSWORD'),
        'HOST': get_env_value('DATABASE_HOST'),
        'PORT': get_env_value('DATABASE_PORT')
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:6379/0",
        "MAX_ENTRIES": 5000,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        }
    },
    "session": {
        "MAX_ENTRIES": 1000,
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        }
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'ru-RU'
# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

TINYMCE_EDITOR_STYLE = '.mcecontentbody{' \
                       'font-family: \'OpenSans-Light\', sans-serif;' \
                       'font-size:13px;' \
                       'color:#000;' \
                       'padding: 30px;' \
                       'box-shadow: 0px 3px 10px rgba(233, 233, 233, 1);' \
                       '}'

TINYMCE_DEFAULT_CONFIG = {
    'theme': "advanced",
    'selector': "textarea",
    "resize": 'both',
    'invalid_elements': "span",
    'width': '70%',
    'height': 500,
    'content_style': TINYMCE_EDITOR_STYLE,
}

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "session"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# STATIC_URL = '/static/'
# STATIC_ROOT = '/home/Martis/WeatlhView/static'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# if DEBUG:
#    STATIC_ROOT = os.path.join(BASE_DIR, '/static')
# else:
#    STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATIC_URL = '/staticfiles/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 587

if ENVIRONMENT == 'PRODUCTION':
    EMAIL_HOST_USER = "noreply@wealthview.info"
    EMAIL_HOST_PASSWORD = "djnQCcurSSWx5uGet"
if ENVIRONMENT == 'DEVELOP':
    EMAIL_HOST_USER = "noreplay@wealthview.info"
    EMAIL_HOST_PASSWORD = "tCfnOh9whM9EqYx"

EOD_SERVICE_API_KEY_RAW = "3fa9o8ba134f90.20329410"  # Ключ доступа к данным для запросов по API
EOD_SERVICE_API_KEY = "&api_token=3fa9o8ba134f90.20329410"  # Ключ доступа к данным для запросов по API
EOD_SERVICE_URL = "https://eodhistoricaldata.com/api/eod/"  # Сайт-источник финасовых данных
EOD_SERVICE_JSON_FMT = "&fmt=json"  # Формат выгрузки данных с источника (изпользуем json)

RISK_PROFILE_NOTIFICATION_INTERVAL = 7

LOGIN_URL = 'login'
AUTHENTICATION_BACKENDS = ['auth_sys.backends.EmailModelBackend']

if IS_LOCAL_ENVIRONMENT is False:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': True,

        'handlers': {
            'logstash': {
                'level': 'INFO',
                'class': 'logstash.TCPLogstashHandler',
                'host': os.environ.get('DJANGO_LOGSTASH_HOST', '188.120.225.230'),
                'port': os.environ.get('DJANGO_LOGSTASH_PORT', 5000),
                'version': 1,
                'message_type': 'logstash',
                'fqdn': True,
                'tags': [ENVIRONMENT],
            },
        },
        'loggers': {
            'logstash': {
                'handlers': ['logstash'],
                'level': 'DEBUG',
                'propagate': True,
            },
        },
    }

# INTERNAL_IPS = ['127.0.0.1'] #  для debug toolbar
