# Generated by Django 2.2.3 on 2019-08-20 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_ticker', models.CharField(max_length=32, verbose_name='Тикер')),
                ('name', models.CharField(max_length=64, verbose_name='Полное название актива')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Актив',
                'verbose_name_plural': 'Активы',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('ticker', models.CharField(help_text="Например: для 'Рубль' -> 'RUB'", max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Тикер')),
                ('name', models.CharField(max_length=32, null=True, unique=True, verbose_name='Наименование валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='DatesOfPricesUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, max_length=50, verbose_name='Дата добавления')),
                ('status', models.CharField(choices=[('s', 'Started'), ('f', 'Completed')], default='s', max_length=60, verbose_name='Статус обновления')),
            ],
            options={
                'verbose_name': 'Дата обновления',
                'verbose_name_plural': 'Даты обновления',
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='Код биржи')),
                ('name', models.CharField(max_length=64, null=True, unique=True, verbose_name='Название биржи')),
            ],
            options={
                'verbose_name': 'Биржа',
                'verbose_name_plural': 'Биржи',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('slug', models.CharField(help_text="Например: для 'Mutual Fond' -> 'MF'", max_length=2, primary_key=True, serialize=False, unique=True, verbose_name='Код в базе данных')),
                ('title', models.CharField(max_length=32, null=True, unique=True, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип актива',
                'verbose_name_plural': 'Типы активов',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начальная дата')),
                ('end_date', models.DateField(verbose_name='Конечная дата')),
                ('investment_sum', models.FloatField(verbose_name='Сумма инвестиций')),
                ('benchmark', models.ForeignKey(default=21891, limit_choices_to={'type_id__in': ['ET', 'MF', 'AC']}, on_delete=django.db.models.deletion.CASCADE, to='backtest.Asset', verbose_name='Бенчмарк')),
                ('currency', models.ForeignKey(limit_choices_to={'ticker__in': ['RUB', 'USD']}, on_delete=django.db.models.deletion.CASCADE, to='backtest.Currency', verbose_name='Валюта инвестиций')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL, verbose_name='Владелец портфеля')),
            ],
            options={
                'verbose_name': 'Портфель',
                'verbose_name_plural': 'Портфели',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.FloatField(verbose_name='Доля актива портфеле')),
                ('asset', models.ForeignKey(limit_choices_to={'type_id__in': ['ET', 'CS', 'ST', 'MF']}, on_delete=django.db.models.deletion.CASCADE, to='backtest.Asset', verbose_name='Актив')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='backtest.Portfolio', verbose_name='Портфель инвестиции')),
            ],
            options={
                'verbose_name': 'Инвестиция',
                'verbose_name_plural': 'Инвестиции',
            },
        ),
        migrations.CreateModel(
            name='AssetsSplits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата дробления')),
                ('split', models.CharField(max_length=32, verbose_name='Коэффициент дробления')),
                ('belongs_to', models.ForeignKey(editable=False, limit_choices_to={'type_id__in': ['ET', 'CS', 'ST', 'MF']}, on_delete=django.db.models.deletion.CASCADE, to='backtest.Asset', verbose_name='Актив')),
            ],
            options={
                'verbose_name': 'Дробление актива',
                'verbose_name_plural': 'Дробления активов',
            },
        ),
        migrations.CreateModel(
            name='AssetsPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('d', 'Day'), ('w', 'Week'), ('m', 'Month')], max_length=5, verbose_name='Интервалы')),
                ('price', models.FloatField(verbose_name='Цена актива')),
                ('date', models.DateField(verbose_name='Дата')),
                ('price_after_split', models.FloatField(verbose_name='Цена после дробления')),
                ('asset', models.ForeignKey(editable=False, limit_choices_to={'type_id__in': ['ET', 'CS', 'ST', 'MF']}, on_delete=django.db.models.deletion.CASCADE, to='backtest.Asset', verbose_name='Актив')),
            ],
            options={
                'verbose_name': 'Цена на актив',
                'verbose_name_plural': 'Цены на активы',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backtest.Currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='asset',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backtest.Exchange', verbose_name='Биржа'),
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtest.Type', verbose_name='Тип актива'),
        ),
    ]
