# Generated by Django 2.2.3 on 2019-08-20 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0002_auto_20190820_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backtest.Currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backtest.Exchange', verbose_name='Биржа'),
        ),
    ]
