# Generated by Django 2.2.3 on 2019-08-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0003_auto_20190820_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='exchange_ticker',
            field=models.CharField(max_length=255, verbose_name='Тикер'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Полное название актива'),
        ),
    ]
