# Generated by Django 2.2.3 on 2019-08-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0004_auto_20190820_1923'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assetsprices',
            index=models.Index(fields=['asset'], name='backtest_as_asset_i_a90032_idx'),
        ),
        migrations.AddIndex(
            model_name='assetssplits',
            index=models.Index(fields=['belongs_to'], name='backtest_as_belongs_0a01e2_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['portfolio'], name='backtest_in_portfol_93ad00_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['asset'], name='backtest_in_asset_i_302b77_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['owner'], name='backtest_po_owner_i_a173bb_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['currency'], name='backtest_po_currenc_714a99_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['benchmark'], name='backtest_po_benchma_88b5bc_idx'),
        ),
    ]
