# Generated by Django 2.2.3 on 2019-08-22 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0005_auto_20190821_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активная'),
        ),
        migrations.AlterField(
            model_name='assetssplits',
            name='belongs_to',
            field=models.ForeignKey(limit_choices_to={'type_id__in': ['ET', 'CS', 'ST', 'MF']}, on_delete=django.db.models.deletion.CASCADE, to='backtest.Asset', verbose_name='Актив'),
        ),
    ]
