# Generated by Django 2.2.3 on 2019-08-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0006_auto_20190822_1311'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['exchange_ticker'], name='backtest_as_exchang_a09ffd_idx'),
        ),
    ]
