# Generated by Django 2.2.3 on 2019-08-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0007_auto_20190822_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='price_update_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата бновления цен'),
        ),
        migrations.AddField(
            model_name='asset',
            name='split_update_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата бновления сплитов'),
        ),
    ]
