# Generated by Django 2.2.3 on 2019-08-23 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0008_auto_20190822_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='price_update_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата обновления цен'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='split_update_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата обновления сплитов'),
        ),
        migrations.AlterField(
            model_name='assetssplits',
            name='belongs_to',
            field=models.ForeignKey(limit_choices_to={'type_id__in': ['ET', 'CS', 'ST', 'MF']}, on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='backtest.Asset', verbose_name='Актив'),
        ),
    ]
