# Generated by Django 2.2.3 on 2019-08-25 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0009_auto_20190823_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Ошибка'), (0, 'Ожидает парсинга'), (1, 'Парсинг сплитов'), (2, 'Парсинг цен'), (3, 'Актуален')], default=0),
        ),
        migrations.AlterField(
            model_name='assetsprices',
            name='asset',
            field=models.ForeignKey(limit_choices_to={'type_id__in': ['ET', 'CS', 'ST', 'MF']}, on_delete=django.db.models.deletion.CASCADE, to='backtest.Asset', verbose_name='Актив'),
        ),
        migrations.AlterField(
            model_name='assetssplits',
            name='belongs_to',
            field=models.ForeignKey(limit_choices_to={'type_id__in': ['ET', 'CS', 'ST', 'MF']}, on_delete=django.db.models.deletion.CASCADE, to='backtest.Asset', verbose_name='Актив'),
        ),
    ]
