# Generated by Django 2.2.3 on 2019-08-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0010_auto_20190825_1302'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='backtest_as_status_eeadea_idx'),
        ),
    ]
