# Generated by Django 2.2.3 on 2019-08-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0011_auto_20190825_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_parse_splits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Ошибка'), (0, 'Ожидает парсинга'), (1, 'Парсинг сплитов'), (2, 'Парсинг цен'), (3, 'Обновление текущих цен'), (4, 'Актуален')], default=0, verbose_name='Статус'),
        ),
    ]
