# Generated by Django 2.2.3 on 2019-11-05 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0012_auto_20190825_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetsprices',
            options={'ordering': ['-date'], 'verbose_name': 'Цена на актив', 'verbose_name_plural': 'Цены на активы'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_parse_splits',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='assetsprices',
            name='asset',
            field=models.ForeignKey(limit_choices_to={'type_id__in': ['ET', 'CS', 'ST', 'MF']}, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='backtest.Asset', verbose_name='Актив'),
        ),
    ]
