# Generated by Django 2.2.3 on 2019-11-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0013_auto_20191105_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetFundAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_attributes', to='backtest.Asset', verbose_name='Фунд. аттрибуты')),
            ],
        ),
    ]
