# Generated by Django 2.2.3 on 2019-11-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0014_assetfundattributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetfundattributes',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объект инвестирования'),
        ),
        migrations.AddField(
            model_name='assetfundattributes',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Эмитент'),
        ),
        migrations.AddField(
            model_name='assetfundattributes',
            name='country_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Рынок'),
        ),
        migrations.AddField(
            model_name='assetfundattributes',
            name='currency_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта торгов'),
        ),
        migrations.AddField(
            model_name='assetfundattributes',
            name='exchange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Биржа'),
        ),
        migrations.AddField(
            model_name='assetfundattributes',
            name='isin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ISIN'),
        ),
        migrations.AddField(
            model_name='assetfundattributes',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='assetfundattributes',
            name='сode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тикер'),
        ),
    ]
