# Generated by Django 2.2.3 on 2019-11-05 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0015_auto_20191105_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='fund_attributes_update_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата обновления аттрибутов'),
        ),
        migrations.AlterField(
            model_name='assetfundattributes',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fund_attributes', to='backtest.Asset', verbose_name='Фунд. аттрибуты'),
        ),
    ]
