# Generated by Django 2.2.3 on 2019-11-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0016_auto_20191105_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetfundattributes',
            name='dividend_share',
            field=models.FloatField(blank=True, null=True, verbose_name='Размер дивиденда'),
        ),
        migrations.AddField(
            model_name='assetfundattributes',
            name='dividend_yield',
            field=models.FloatField(blank=True, null=True, verbose_name='Дивидендная доходность'),
        ),
        migrations.AddField(
            model_name='assetfundattributes',
            name='ex_dividend_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата див. отсечки'),
        ),
        migrations.AddField(
            model_name='assetfundattributes',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отрасль'),
        ),
        migrations.AddField(
            model_name='assetfundattributes',
            name='market_capitalization',
            field=models.FloatField(blank=True, null=True, verbose_name='Рыночная капитализация'),
        ),
        migrations.AddField(
            model_name='assetfundattributes',
            name='report_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отчетности'),
        ),
        migrations.AddField(
            model_name='assetfundattributes',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сектор'),
        ),
    ]
