# Generated by Django 2.2.3 on 2019-12-13 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0017_auto_20191112_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsprices',
            name='asset',
            field=models.ForeignKey(limit_choices_to={'type_id__in': ['ET', 'CS', 'ST', 'MF', 'AC']}, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='backtest.Asset', verbose_name='Актив'),
        ),
        migrations.AlterField(
            model_name='assetssplits',
            name='belongs_to',
            field=models.ForeignKey(limit_choices_to={'type_id__in': ['ET', 'CS', 'ST', 'MF', 'AC']}, on_delete=django.db.models.deletion.CASCADE, to='backtest.Asset', verbose_name='Актив'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='asset',
            field=models.ForeignKey(limit_choices_to={'type_id__in': ['ET', 'CS', 'ST', 'MF', 'AC']}, on_delete=django.db.models.deletion.CASCADE, to='backtest.Asset', verbose_name='Актив'),
        ),
    ]
