# Generated by Django 2.2.3 on 2020-04-07 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0019_auto_20200204_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsprices',
            name='asset',
            field=models.ForeignKey(limit_choices_to={'type_id__in': ['ET', 'ST', 'CS']}, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='backtest.Asset', verbose_name='Актив'),
        ),
        migrations.AlterField(
            model_name='assetssplits',
            name='belongs_to',
            field=models.ForeignKey(limit_choices_to={'type_id__in': ['ET', 'ST', 'CS']}, on_delete=django.db.models.deletion.CASCADE, to='backtest.Asset', verbose_name='Актив'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='asset',
            field=models.ForeignKey(limit_choices_to={'type_id__in': ['ET', 'ST', 'CS']}, on_delete=django.db.models.deletion.CASCADE, to='backtest.Asset', verbose_name='Актив'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='benchmark',
            field=models.ForeignKey(default=21891, limit_choices_to={'type_id__in': ['ET', 'AC']}, on_delete=django.db.models.deletion.CASCADE, to='backtest.Asset', verbose_name='Бенчмарк'),
        ),
    ]
