# Generated by Django 2.2.3 on 2020-06-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0020_auto_20200407_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='benchmark',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
