# Generated by Django 2.2.3 on 2020-09-06 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0021_auto_20200602_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Ошибка'), (0, 'Ожидает парсинга'), (1, 'Парсинг сплитов'), (2, 'Парсинг цен'), (3, 'Обновление текущих цен'), (4, 'Актуален'), (5, 'Устарел')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='assetsprices',
            name='asset',
            field=models.ForeignKey(limit_choices_to={'type_id__in': ['ET', 'ST', 'FX']}, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='backtest.Asset', verbose_name='Актив'),
        ),
        migrations.AlterField(
            model_name='assetssplits',
            name='belongs_to',
            field=models.ForeignKey(limit_choices_to={'type_id__in': ['ET', 'ST', 'FX']}, on_delete=django.db.models.deletion.CASCADE, to='backtest.Asset', verbose_name='Актив'),
        ),
    ]
