# Generated by Django 3.1.1 on 2020-11-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0022_auto_20200906_1558'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('exchange_ticker', 'exchange')},
        ),
    ]
