# Generated by Django 2.2.3 on 2019-08-20 15:31

import WealthView.utils
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название категории', max_length=64, null=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Родительская категория (если имеется)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='articles.Category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок статьи', max_length=128)),
                ('slug', models.SlugField(blank=True, help_text='Генерируется автоматически по заголовку', max_length=128, unique=True)),
                ('thumbnail', models.ImageField(blank=True, default='media/img/articles/default_thumb.png', help_text='Превью-изображение для статьи.', upload_to=WealthView.utils.path_and_rename)),
                ('content', tinymce.models.HTMLField(help_text='Содержание статьи')),
                ('date', models.DateTimeField()),
                ('seo_title', models.CharField(blank=True, help_text='Заголовок статьи для SEO', max_length=128)),
                ('category', models.ForeignKey(help_text='Подкатегория для статьи', on_delete=django.db.models.deletion.PROTECT, to='articles.Category')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
