# Generated by Django 2.2.3 on 2020-04-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20191213_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, help_text='Описание статьи', max_length=500),
        ),
    ]
