# Generated by Django 2.2.3 on 2020-08-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200407_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Генерируется автоматически по заголовку', max_length=128, unique=True),
        ),
    ]
